<a href="https://colab.research.google.com/github/m-santh/AicoreKaggle/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

import os
#os.chdir("../../Kaggle/")

from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 

data_X = np.load('/content/drive/MyDrive/AiCore/X_train.npy')
data_Y = np.load('/content/drive/MyDrive/AiCore/y_train.npy')
data_Y = data_Y.astype(int) 
test_data = np.load('/content/drive/MyDrive/AiCore/X_test.npy')

print(np.shape(data_X))

print(np.shape(data_Y))

print(np.shape(test_data))


X_train, X_test, y_train, y_test = train_test_split(data_X, data_Y, random_state = 0)

from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train) 
  
# accuracy on X_test 
accuracy = knn.score(X_test, y_test) 
print(accuracy)
  
# creating a confusion matrix 
knn_predictions = knn.predict(X_test)  
cm = confusion_matrix(y_test, knn_predictions) 
print(cm)

(10000, 100)
(10000,)
(40000, 100)
0.3024
[[126   3  25   6  14   4  12   8  52   3]
 [ 22  44  26   7  31  10  36   6  50  13]
 [ 25   2  99  11  57  10  22   5   8   0]
 [ 18   1  57  49  45  25  42   7   8   1]
 [ 23   3  73  11  91   5  31   6  12   0]
 [ 12   4  67  35  46  43  37   9   5   2]
 [  7   2  69   8  63   7  83   2   3   1]
 [ 22   1  56  14  68   7  20  43   8   6]
 [ 43   8  18   5  11   2   5   3 145   3]
 [ 44  24  30  10  21   4  23  16  57  33]]


In [ ]:
cm.